name: telegram-chatbot

services:
  server:
    container_name: telegram-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    mem_limit: 1G
    env_file:
      - path: .env
        required: true
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./storage:/app/storage