/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MessageRole = "assistant" | "tool" | "user";

export type OutputFormat = "audio" | "embedding" | "image" | "text" | "video";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Messages {
  asset: Json | null;
  chat_id: Int8;
  content: string;
  created_at: Timestamp;
  id: Generated<Int8>;
  model: string | null;
  role: MessageRole;
  thread_id: Int8;
  updated_at: Timestamp | null;
}

export interface Models {
  id: Generated<Int8>;
  is_enabled: boolean;
  model_context_length: number | null;
  model_description: string | null;
  model_id: string;
  model_name: string;
  provider_id: string;
}

export interface Providers {
  id: string;
  name: string;
}

export interface Threads {
  chat_id: Int8;
  context_messages: number;
  created_at: Timestamp;
  data: Json | null;
  last_command: string | null;
  max_messages_in_context: number;
  model_id: Int8 | null;
  next_step: number | null;
  output_format: OutputFormat;
  system_prompt: string;
  thread_id: Int8;
  title: string | null;
  token_usage: number;
  updated_at: Timestamp | null;
}

export interface Users {
  created_at: Timestamp;
  default_model_id: Int8 | null;
  first_name: string | null;
  id: Int8;
  last_name: string | null;
  updated_at: Timestamp | null;
  username: string | null;
}

export interface DB {
  messages: Messages;
  models: Models;
  providers: Providers;
  threads: Threads;
  users: Users;
}
